site_name: Lilevitchi | Guides de Modding
site_url: https://lilevitchi.github.io/

theme:
  name: material
  logo: assets/logo.png # Ton logo apparaîtra dans la barre de menu
  favicon: assets/logo.png
  language: fr
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black # On teste noir pour faire ressortir ton logo
      accent: deep orange
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Accueil: index.md
  - Fallout 4:
      - Introduction: fallout4/intro.md
      - Installation: fallout4/setup.md
  - Fallout London: fallout-london/index.md
  - Fallout New Vegas: fnv/index.md
  - Tale of Two Wastelands: ttw/index.md
  - Cyberpunk 2077: cyberpunk/index.md
