site_name: Lilevitchi | Modding
site_url: https://lilevitchi.github.io/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - stylesheets/extra.css

# Cette partie force le site à utiliser toute la largeur disponible
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Accueil: index.md
  - Guide Fallout 4:
      - Introduction: fallout4/intro.md
      - Installation: fallout4/setup.md
  - Fallout London: fallout-london/index.md
  - Fallout New Vegas: fnv/index.md
  - Tale of Two Wastelands: ttw/index.md
  - Cyberpunk 2077: cyberpunk/index.md
